import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LenguageSelector from '../components/LenguageSelector' 
import Link from 'next/link'
import  { useRouter} from 'next/router'
export default function Home(props) {


  const router = useRouter()


  const {home} = props
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LenguageSelector></LenguageSelector>
        <h1 className={styles.title}>
         {home.welcome}
        </h1>
        <p>
          <Link href='/contact' locale={router.locale}>
            <a>
              {home.link}
            </a>
          </Link>
        </p>
      </main>
    </div>  
  )
}


export async function getStaticProps({locale}){
    


  //example if we work with a server for search the languages
  // const response = await fetch("URL")
  // const result = await response.json()

  // it show you this in your terminal or cmd
  // console.log(locale)
  
  const response = await import(`../lang/${locale}.json`) 

 


  return {
      props: {
          home: response.default.home
      }
  }

}